version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

  database:
    image: mysql:latest
    container_name: database
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=library
    volumes:
      - ./.data:/var/lib/mysql
